### ISSUE TITLE
fix the description command 'create help'

### ISSUE THREAD

**Issue by DimaSidorenko** [scaffold-project/scaffold#10]
[options] should be after create <template-name>

Bug example: ![image](https://user-images.githubusercontent.com/60537382/119248446-998e3400-bbaa-11eb-9ce3-1d22ad0013cb.png)

**Comment by iskorotkov** [comment]
Лучше давай писать только на Trello, чтобы всё было в одном месте.

Создал карточку [на Trello](https://trello.com/c/v3WnrMdb/54-options-should-be-after-create)
